spring.application.name=demo

#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/demo_db}
#spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:}

spring.datasource.username=sql12831684
spring.datasource.password=98XkREcjJV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12831684?useUnicode=true&characterEncoding=UTF-8

jwt.secret=${JWT_SECRET:mySecretKey123456789012345678901234567890}
jwt.expiration=86400000

server.address=0.0.0.0